repos:
  - repo: local
    hooks:
      - id: build-check
        name: Build
        language: system
        entry: npm run build
        stages: [pre-commit]
        pass_filenames: false

      - id: lint
        name: Lint
        language: system
        entry: npm run lint
        stages: [pre-commit]
        pass_filenames: false

      - id: type-check
        name: Type Check
        language: system
        entry: npm run type-check
        stages: [pre-commit]
        pass_filenames: false

      - id: test
        name: Test
        language: system
        entry: npm run type-check
        stages: [pre-commit]
        pass_filenames: false
