repos:
  - repo: local
    hooks:
      - id: type-check
        name: Try to type-check
        language: system
        entry: pnpm run lint
        stages: [commit]
        pass_filenames: false

      - id: build
        name: Try to build
        language: system
        entry: pnpm run build
        stages: [commit]
        pass_filenames: false

      - id: lint
        name: Try to lint
        language: system
        entry: pnpm lint
        stages: [commit]
        pass_filenames: false

      - id: format
        name: Try to format
        language: system
        entry: pnpm format
        stages: [commit]
        pass_filenames: false

      - id: build-storybook
        name: Build latest storybook
        language: system
        entry: pnpm run build-storybook
        stages: [commit]
        pass_filenames: false
