name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}

    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        with:
          path: docs
          build_command: npm run build-storybook
