name: Build and Deploy Storybook

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          pnpm install
          pnpm run build-storybook
      - name: Deploy Storybook 🚀
        run: | # Deploy the Storybook files to GitHub Pages
          pnpm run deploy-storybook
