name: Test

on:
  push:
    branches: [main, dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Install dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm run test
